Various bug fixes and small enhancements
MD-Anderson-Bioinformatics/NG-CHM pull request #431
Opened 2023-02-28 12:29 UTC by bmbroom

Note: I have not addressed the keyboard navigation issues in this pull request.

Note: increment version number immediately prior to merging

2023-03-02 18:49 UTC, jmelott requested changes
I'd question the usefulness or desire to show the youtube videos in an iframe in the viewer.  That eliminates a lot of the usefulness of the videos of being able to play them alongside the ngchm while you're trying things out.  It stops access to the other elements on the youtube page like the time links and other things.  I think it would be better to open the playlist in another tab instead.

2023-03-03 14:08 UTC, bmbroom commented
We can discuss Monday.  I find it's a more efficient use of screen space than having a separate window.  (At least on Mac and perhaps Windows. I don't know how to make a window "always on top" on either of those systems like you can on Linux.)

It's very easy to open a new tab from the popup by clicking on the "Watch on Youtube" button.  It's not possible to go the other way.

I don't understand your comment about not being able to watch the videos while trying things out.  Except for a couple of popups dismissing the videos, I was able to do so.  Those cases will have to be fixed if we decide to go ahead with this idea.

2023-03-03 15:06 UTC, jmelott commented
I hadn't actually tried playing the video, but if it is not modal then people can still use the map, then that's OK.

2023-03-03 15:06 UTC, jmelott approved these changes

2023-03-07 17:10 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/Linkout.js
> +		LNK.addLinkout("Copy bar data for all columns", "ColumnCovar", linkouts.MULTI_SELECT, LNK.copyEntireClassBarToClipBoard,null,0);
Change in 3rd arg from null to MULTI_SELECT is unclear.  Same issue just below.

2023-03-07 17:17 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/Linkout.js
> +			const covar = axis.indexOf('Covar') != -1;
i.e. axis is RowCovar or ColumnCovar.  A future rewrite of Linkout.js should eliminate magic name strings.

2023-03-07 17:21 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/Linkout.js
> +					if (covar && grpLinkouts[l].linkout.title.indexOf('for selected') != -1 &&
Another magic string.  Logic should be reversed (negated).

2023-03-07 17:23 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/DetailHeatMapEvent.js
> +			if (document.querySelector('.ClassBar[data-axis="' + axis + '"][data-index="' + idx + '"]')) {
Using DOM state?  Is this the way we model shown/hidden?

2023-03-07 17:30 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/NGCHM_Util.js
> +	 if (e.ctrlKey) {
No problem with this, but this function should be reviewed and rewritten or commented.

2023-03-07 17:45 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/Customization.js
> +	    initScript();
i.e. the call to initScript() is edited out ?  (One?)

2023-03-07 17:48 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/Customization.js
> +	    // Most browsers:
So the Minimizer no longer modifies this block?

2023-03-07 17:56 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/UI-Manager.js
> +					if (!mapItem) return;
"mapItem" is always either =primaryMap or null ?  If that's true, I suggest naming the variable primaryMap.

2023-03-07 18:00 UTC, ChrisWakefield commented on NGCHM/WebContent/css/NGCHM.css
> +    width: 250px;
Seconding your comment in the commit message.  Would be better to not be sensitive to width of fonts/labels.

2023-03-07 19:06 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/PdfGenerator.js
>  			// If widgetized viewer exclude MDA logo and show compressed hear
Does this (old) comment make sense to anyone?  ("show compressed hear")

2023-03-07 19:12 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/PdfGenerator.js
> +PDF.pdfDialogClosed = function() {
Shouldn't "PDF Dialog" be modal?  With a function like jquery's modaldialog(), this logic isn't needed. (?)

2023-03-07 19:26 UTC, ChrisWakefield commented on NGCHM/WebContent/javascript/UserPreferenceManager.js
>  }
Factor out enableApplyButton() so it's clear it is called in all cases.

2023-03-07 20:02 UTC, ChrisWakefield approved these changes
Based on only code review, made a number of comments, but otherwise ok.

2023-03-08 20:43 UTC, bmbroom commented
After discussion with Chris, I will merge this pull request now without incrementing the version number.  The version number will dump just before merging the third pull request in the current group.

2023-03-08 20:44 UTC, merged